- name: Install modules
  hosts: webservers
  become: yes
  vars:
    apt_package: [git, python-dev, python-virtualenv, libssl-dev, libffi-dev, tree]
    gather_tasks: no # saves a lot of time
  vars_prompt: 
    - name: "branch"
      prompt: "Which version of horizon do you want to install?"
      default: "master"

  tasks:
    - name: Clone horizon
      git: repo=https://github.com/openstack/horizon.git
           dest=/home/uuuu/horizon/
           version={{ branch }}
           accept_hostkey=True
           clone=no
           update=yes
      notify: 
        - Copy local settings example

#    - name: Install horizon script
#      command: ./run_tests.sh -V chdir=/home/uuuu/horizon/
  handlers: 
    - name: Copy local settings example
      command: cp openstack_dashboard/local/local_settings.py.example openstack_dashboard/local/local_settings.py chdir=/home/uuuu/horizon/ 
