---
- name: Clone horizon
  git: repo=https://github.com/openstack/horizon.git
       dest=/home/uuuu/horizon/
       version=stable/liberty
       accept_hostkey=True
       clone=no
       update=yes
  notify:
    - Copy local settings example

