- name: Local HyperV setup
  hosts: localhost
  become: yes
  tasks: 
    - name: Install vagrant
      apt: name=vagrant update_cache=yes

- name: Install modules
  hosts: webservers
  become: yes
  vars:
    apt_package: [git, python-dev, python-virtualenv, libssl-dev, libffi-dev, tree]
    gather_tasks: no # saves a lot of time
  vars_prompt: 
    - name: "branch"
      prompt: "Which version of horizon do you want to install?"
      default: "master"

  tasks:
    - name: Install dependencies
      apt: name={{item}} update_cache=yes
      with_items: "{{apt_package}}"
      become: yes
      when: ansible_os_family == "Debian"

    - name: Ensure github.com is a known host # lookup module added else git clone fails
      lineinfile:
        dest: /root/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com" # add known hosts here

    - name: Clone horizon
      git: repo=https://github.com/openstack/horizon.git
           dest=/home/uuuu/horizon/
           version={{ branch }}
           accept_hostkey=True
           clone=no
           update=no

#    - name: Install horizon script
#      command: ./run_tests.sh -V chdir=/home/uuuu/horizon/

    - name: Copy local settings example
      command: cp openstack_dashboard/local/local_settings.py.example openstack_dashboard/local/local_settings.py chdir=/home/uuuu/horizon/ 

    - name: Make sure you are running with venv
      command: ./with_venv.sh chdir=/home/uuuu/horizon/tools/
      become: yes

    - name: Start service apache2 if not started
      service: name=apache2 state=restarted
      become: yes
