- name: Install horizon prerequisites
  hosts: webservers
  sudo: True
  vars:
    apt_package: [git, python-dev, python-virtualenv, libssl-dev, libffi-dev]
  tasks:
    - name: install deps
      apt: name={{item}} update_cache=yes
      with_items: "{{apt_package}}"
      become: yes
