- name: Install modules
  hosts: webservers
  become: yes
  vars:
    apt_package: [git, python-dev, python-virtualenv, libssl-dev, libffi-dev, tree]
  tasks:
    - name: install deps
      apt: name={{item}} update_cache=yes
      with_items: "{{apt_package}}"
      become: yes
