- name: Install modules
  hosts: webservers
  become: yes
  vars:
    apt_package: [git, python-dev, python-virtualenv, libssl-dev, libffi-dev, tree]
    gather_tasks: no # saves a lot of time
  tasks:
    - name: Install dependencies
      apt: name={{item}} update_cache=yes
      with_items: "{{apt_package}}"
      become: yes
    - name: Start service apache2 if not started
      service: name=apache2 state=restarted
      become: yes
